[package]
name = "fitbit_lib"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-sheets4 = "1.0"
hyper = "0.10"
hyper-native-tls = "0.3.0"
yup-oauth2 = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
garmin_lib = {path = "../garmin_lib"}
failure = "0.1"