[package]
name = "fitbit_lib"
version = "0.4.51"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-sheets4 = "1.0"
hyper = "0.10"
hyper-native-tls = "0.3.0"
yup-oauth2 = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
garmin_lib = {path = "../garmin_lib"}
failure = "0.1"
chrono = "0.4"
telegram-bot = "0.6"
futures = "0.1"
tokio-core = "0.1"
dotenv = "0.15"
crossbeam-channel = "0.3"
cpython = "0.3"
glob = "0.3"
rayon = "1.2"
log = "0.4"
lazy_static = "1.4"
parking_lot = "0.9"
crossbeam-utils = "0.6"
