[package]
name = "fitbit_lib"
version = "0.8.60"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
garmin_lib = {path = "../garmin_lib"}
garmin_connect_lib = {path = "../garmin_connect_lib"}
chrono = "0.4"
dotenv = "0.15"
crossbeam-channel = "0.4"
glob = "0.3"
rayon = "1.3"
log = "0.4"
lazy_static = "1.4"
parking_lot = "0.11"
crossbeam-utils = "0.7"
structopt = "0.3"
itertools = "0.9"
avro-rs = {version = "0.10", features = ["snappy"]}
tempfile = "3.1"
postgres_query = "0.3"
anyhow = "1.0"
thiserror = "1.0"
tokio = {version="0.2", features=["full"]}
futures = "0.3"
reqwest = {version="0.10", features=["cookies", "json", "rustls-tls", "stream"], default_features=false}
rand = "0.7"
base64 = "0.12"
maplit = "1.0"
bytes = "0.5"
statistical = "1.0"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.3", features=["postgres_types"] }
fitparser = "0.2"
