[package]
name = "garmin_rust"
version = "0.1.13"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
flate2 = "1.0"
failure = "0.1"
rayon = "1.0"
chrono = "0.4"
approx = "0.3"
subprocess = "0.1"
json = "0.11"
postgres = "0.15"
postgres-derive = "0.3"
native-tls = "*"
clap = "2"
log = "0.4"
env_logger = "0.6"
rusoto_core = {version = "0.36", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.36", default_features = false, features=["rustls"]}
futures = "*"
# s4 = "*"
num = "*"
config = "*"
tempdir = "*"
tempfile = "*"
actix-web = "*"
actix = "*"
rand = "0.6"
lambda_runtime = "*"
simple_logger = "1.0"
r2d2 = "*"
r2d2_postgres = "*"
dotenv = "*"
rust_auth_server = {git = "https://github.com/ddboline/rust-auth-server.git", tag="0.1.1"}

[dependencies.avro-rs]
version = "^0.6"
features = ["snappy"]

[lib]
name = "garmin_rust"
path = "src/lib.rs"

[[bin]]
name = "garmin-rust-proc"
path = "src/garmin_rust_proc.rs"
doc = false

[[bin]]
name = "garmin-rust-report"
path = "src/garmin_rust_report.rs"
doc = false

[[bin]]
name = "garmin-rust-http"
path = "src/garmin_rust_http.rs"
doc = false

[[bin]]
name = "bootstrap"
path = "src/garmin_lambda.rs"
doc = false
