[package]
name = "garmin_rust"
version = "0.9.34"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
fitbit_lib = {path="fitbit_lib"}
garmin_cli = {path="garmin_cli"}
garmin_lib = { path = "garmin_lib" }
garmin_http = { path = "garmin_http" }
strava_lib = { path = "strava_lib" }
fitbit_bot = {path="fitbit_bot"}
garmin_connect_lib = {path="garmin_connect_lib"}
race_result_analysis = {path="race_result_analysis"}
garmin_reports = {path="garmin_reports"}
actix-web =  "3.2"
log = "0.4"
env_logger = "0.8"
crossbeam-utils = "0.8"
structopt = "0.3"
anyhow = "1.0"
thiserror = "1.0"
tokio = {version="0.2", features=["full"]}
dirs = "3.0"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.9", features=["postgres_types"] }

[dev-dependencies]
approx = "0.4"

[workspace]
members = [
    "fitbit_lib",
    "garmin_cli",
    "garmin_lib",
    "garmin_http",
    "strava_lib",
    "fitbit_bot",
    "garmin_connect_lib",
    "race_result_analysis",
    "garmin_reports",
]

[[bin]]
name = "garmin-rust-http"
path = "src/garmin_rust_http.rs"
doc = false

[[bin]]
name = "scale-measurement-bot"
path = "src/scale_measurement_bot.rs"
doc = false

[[bin]]
name = "import-fitbit-json-files"
path = "src/import_fitbit_json_files.rs"
doc = false

[[bin]]
name = "garmin-rust-cli"
path = "src/garmin_rust_cli.rs"
doc = false

[[bin]]
name = "import-garmin-connect-data"
path = "src/import_garmin_connect_data.rs"
doc = false
