[package]
name = "garmin_rust"
version = "0.7.15"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
fitbit_lib = {path="fitbit_lib"}
garmin_cli = {path="garmin_cli"}
garmin_lib = { path = "garmin_lib" }
garmin_http = { path = "garmin_http" }
strava_lib = { path = "strava_lib" }
fitbit_bot = {path="fitbit_bot"}
sheets_lib = {path="sheets_lib"}
actix = "0.9"
actix-rt = "1.0"
log = "0.4"
env_logger = "0.7"
crossbeam-utils = "0.7"
structopt = "0.3"
anyhow = "1.0"
thiserror = "1.0"
tokio = {version="0.2", features=["full"]}

[dev-dependencies]
approx = "0.3"

[workspace]
members = [
    "fitbit_lib",
    "garmin_cli",
    "garmin_lib",
    "garmin_http",
    "strava_lib",
    "fitbit_bot",
    "sheets_lib",
]

[[bin]]
name = "garmin-rust-http"
path = "src/garmin_rust_http.rs"
doc = false

[[bin]]
name = "pull-scale-measurements-from-telegram"
path = "src/pull_scale_measurements_from_telegram.rs"
doc = false

[[bin]]
name = "import-fitbit-json-files"
path = "src/import_fitbit_json_files.rs"
doc = false

[[bin]]
name = "garmin-rust-cli"
path = "src/garmin_rust_cli.rs"
doc = false

[[bin]]
name = "pull-scale-measurements-from-sheets"
path = "src/pull_scale_measurements_from_sheets.rs"
doc = false
