[package]
name = "garmin_rust"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.27"
flate2 = "1.0"
failure = "0.1.2"
rayon = "1.0.2"
chrono = "0.4"
approx = "0.3"
subprocess = "*"
json = "*"
postgres = "*"
clap = "*"
log = "*"
env_logger = "*"
rusoto_core = "*"
rusoto_s3 = "*"
rusoto_lambda = "*"
futures = "*"
s4 = "*"
num = "*"
config = "*"
tempdir = "*"
tempfile = "*"
rocket = "*"

[dependencies.avro-rs]
version = "^0.6"
features = ["snappy"]

[lib]
name = "garmin_rust"
path = "src/lib.rs"

[[bin]]
name = "garmin_rust_proc"
path = "src/garmin_rust_proc.rs"
doc = false

[[bin]]
name = "garmin_rust_report"
path = "src/garmin_rust_report.rs"
doc = false

[[bin]]
name = "garmin_rust_http"
path = "src/garmin_rust_http.rs"
doc = false
