[package]
name = "garmin_rust"
version = "0.4.58"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
fitbit_lib = {path="fitbit_lib"}
garmin_lib = { path = "garmin_lib" }
garmin_http = { path = "garmin_http" }
strava_lib = { path = "strava_lib" }
actix = "0.8.3"
actix-rt = "0.2"
log = "0.4"
env_logger = "0.7"
crossbeam-utils = "0.6"
failure = "0.1"
structopt = "0.3"

[workspace]
members = [
    "fitbit_lib",
    "garmin_lib",
    "garmin_http",
    "strava_lib",
]

[[bin]]
name = "garmin-rust-proc"
path = "src/garmin_rust_proc.rs"
doc = false

[[bin]]
name = "garmin-rust-report"
path = "src/garmin_rust_report.rs"
doc = false

[[bin]]
name = "garmin-rust-http"
path = "src/garmin_rust_http.rs"
doc = false

[[bin]]
name = "pull-scale-measurements-from-sheets"
path = "src/pull_scale_measurements_from_sheets.rs"
doc = false

[[bin]]
name = "pull-scale-measurements-from-telegram"
path = "src/pull_scale_measurements_from_telegram.rs"
doc = false

[[bin]]
name = "import-fitbit-json-files"
path = "src/import_fitbit_json_files.rs"
doc = false
