FROM amazonlinux:2017.03
MAINTAINER Daniel Boline

RUN yum install -y gcc g++ openssl-devel zip libusb-devel \
    glibc-static openssl-static pcre-static zlib-static && \
    curl https://sh.rustup.rs > rustup.sh && \
    sh rustup.sh -y && \
    . ~/.cargo/env && \
    rustup target add x86_64-unknown-linux-musl

WORKDIR /garmin_rust

ADD Cargo.toml /garmin_rust
ADD src /garmin_rust/src
ADD scripts /garmin_rust/scripts
ADD lambda /garmin_rust/lambda
ADD Makefile /garmin_rust
