FROM ubuntu:bionic
MAINTAINER Daniel Boline

RUN apt-get update && \
    apt-get install -y curl pkg-config checkinstall gcc libssl-dev ca-certificates \
            file build-essential autoconf automake autotools-dev libtool xutils-dev \
            git libusb-dev libxml2-dev && \
    rm -rf /var/lib/apt/lists/* && \
    curl https://sh.rustup.rs > rustup.sh && \
    sh rustup.sh -y && \
    . ~/.cargo/env

WORKDIR /garmin_rust

ADD Cargo.toml /garmin_rust
ADD src /garmin_rust/src
ADD scripts /garmin_rust/scripts
ADD Makefile /garmin_rust
