FROM rust_stable:latest
LABEL maintainer="Daniel Boline"

WORKDIR /garmin_rust

ADD Cargo.toml /garmin_rust
ADD src /garmin_rust/src
ADD scripts /garmin_rust/scripts
ADD templates /garmin_rust/templates
ADD Makefile /garmin_rust
ADD garmin_cli /garmin_rust/garmin_cli
ADD garmin_lib /garmin_rust/garmin_lib
ADD garmin_http /garmin_rust/garmin_http
ADD fitbit_lib /garmin_rust/fitbit_lib
ADD strava_lib /garmin_rust/strava_lib
ADD fitbit_bot /garmin_rust/fitbit_bot
ADD garmin_connect_lib /garmin_rust/garmin_connect_lib
ADD race_result_analysis /garmin_rust/race_result_analysis
ADD garmin_reports /garmin_rust/garmin_reports
