FROM lambci/lambda:build-provided
MAINTAINER Daniel Boline

RUN yum install -y gcc g++ zip && \
    curl https://sh.rustup.rs > rustup.sh && \
    sh rustup.sh -y && \
    . ~/.cargo/env

WORKDIR /garmin_rust

ADD Cargo.toml /garmin_rust
ADD src /garmin_rust/src
ADD scripts /garmin_rust/scripts
ADD lambda /garmin_rust/lambda
ADD Makefile /garmin_rust
