FROM rust_stable:xenial_latest
MAINTAINER Daniel Boline

WORKDIR /garmin_rust

ADD Cargo.toml /garmin_rust
ADD src /garmin_rust/src
ADD fitbit_lib /garmin_rust/fitbit_lib
ADD garmin_lib /garmin_rust/garmin_lib
ADD garmin_http /garmin_rust/garmin_http
ADD scripts /garmin_rust/scripts
ADD templates /garmin_rust/templates
ADD Makefile /garmin_rust
ADD python /garmin_rust/python
