FROM ubuntu:bionic
LABEL maintainer="Daniel Boline"

RUN echo deb [trusted=yes] https://py2deb-repo.s3.amazonaws.com/deb/bionic/python3 bionic main > /etc/apt/sources.list.d/py2deb.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv 25508FAF711C1DEB && \
    apt-get update && \
    apt-get install garmin-rust

WORKDIR /garmin_rust

ADD Cargo.toml /garmin_rust
ADD src /garmin_rust/src
ADD scripts /garmin_rust/scripts
ADD templates /garmin_rust/templates
ADD Makefile /garmin_rust
ADD garmin_lib /garmin_rust/garmin_lib
ADD garmin_http /garmin_rust/garmin_http
ADD fitbit_lib /garmin_rust/fitbit_lib
ADD strava_lib /garmin_rust/strava_lib
ADD fitbit_bot /garmin_rust/fitbit_bot
ADD garmin_connect_lib /garmin_rust/garmin_connect_lib
ADD race_result_analysis /garmin_rust/race_result_analysis
ADD garmin_reports /garmin_rust/garmin_reports