[package]
name = "strava_lib"
version = "0.4.46"
authors = ["Daniel Boline <dboline@mediamath.com>"]
edition = "2018"

[dependencies]
garmin_lib = { path = "../garmin_lib" }
failure = "0.1"
cpython = "0.3"
tempfile = "3.1"
log = "0.4"
