[package]
name = "strava_lib"
version = "0.11.31"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
garmin_lib = { path = "../garmin_lib" }
tempfile = "3.1"
log = "0.4"
chrono = "0.4"
anyhow = "1.0"
thiserror = "1.0"
reqwest = {version="0.11", features=["cookies", "json", "rustls-tls", "stream", "multipart"], default_features=false}
lazy_static = "1.4"
tokio = {version="1.0", features=["full"]}
tokio-stream = "0.1"
base64 = "0.13"
rand = "0.8"
maplit = "1.0"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
uuid = "0.8"
postgres_query = {git = "https://github.com/ddboline/rust-postgres-query", tag = "0.3.3-2", features=["deadpool"]}
rayon = "1.5"
futures = "0.3"
select = "0.5"
smallvec = "1.6"
chrono-tz = "0.5"
crossbeam-utils = "0.8"
rweb = {version="0.12", features=["openapi"]}
stack-string = { version="0.2", features=["postgres_types", "rweb-openapi"] }
