[package]
name = "strava_lib"
version = "0.1.0"
authors = ["Daniel Boline <dboline@mediamath.com>"]
edition = "2018"

[dependencies]
garmin_lib = { path = "../garmin_lib" }
failure = "0.1"
cpython = "0.3"
