[package]
name = "strava_lib"
version = "0.8.46"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
garmin_lib = { path = "../garmin_lib" }
tempfile = "3.1"
log = "0.4"
chrono = "0.4"
anyhow = "1.0"
thiserror = "1.0"
reqwest = {version="0.10", features=["cookies", "json", "rustls-tls", "stream"], default_features=false}
lazy_static = "1.4"
tokio = {version="0.2", features=["full"]}
base64 = "0.12"
rand = "0.7"
maplit = "1.0"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
uuid = "0.8"
postgres_query = "0.3"
rayon = "1.3"
futures = "0.3"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.3", features=["postgres_types"] }
