[package]
name = "strava_lib"
version = "0.7.17"
authors = ["Daniel Boline <dboline@mediamath.com>"]
edition = "2018"

[dependencies]
garmin_lib = { path = "../garmin_lib" }
cpython = "0.4"
tempfile = "3.1"
log = "0.4"
chrono = "0.4"
anyhow = "1.0"
thiserror = "1.0"
