[package]
name = "race_result_analysis"
version = "0.9.28"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
garmin_lib = {path="../garmin_lib"}
tokio-postgres = {version = "0.5", features = ["with-chrono-0_4"]}
postgres-types = "0.1"
bytes = "0.5"
anyhow = "1.0"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
postgres_query = "0.3"
chrono = "0.4"
tokio = {version="0.2", features=["full"]}
ndarray = "0.13"
parking_lot = "0.11"
lazy_static = "1.4"
itertools = "0.9"
maplit = "1.0"
smallvec = "1.4"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.6", features=["postgres_types"] }
rusfun = { git = "https://github.com/ddboline/rusfun.git", tag="0.3.2" }
